"""One fixed-setting ADC acquisition workflow shared by the CLI and future UI.

The caller owns connection open/close. Preparation is intentional configuration;
acquisition settings are temporary and restored to the state after preparation.

Unlike `HoldScanJob`, there is no swept x-value: `configure_adc_external_hold`
is applied at one fixed operating point and repeated ADC batches are collected
at it, with one CSV row written per (channel, event) pair rather than one
aggregated row per point.
"""

from copy import deepcopy
import csv
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from hashlib import sha256
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
import time

from radioroc_client import (
    ASIC_SHAPER_GAIN_SUBADDRESS, AcquisitionConfig, AcquisitionResult, DEFAULT_CONFIG, I2CRow,
    N_CHANNELS, RadiorocDevice, RadiorocMemoryTransport, RadiorocRunMetadata, bits,
)
from radioroc.data.acquisition import AcquisitionRunWriter
from radioroc.transport.errors import TransportClosedError, TransportIOError, TransportProtocolError
from .jobs import CancellationToken, JobBusyError, JobCancelled, JobEvent, session_lock
from .verification import verify_restoration as run_restoration_check

# The job's own FPGA state footprint to snapshot/restore/verify: ADC hold/timing
# control words. Word 2 is excluded: acquire_adc_batch always leaves it exactly
# where it found it.
_FPGA_ACQUISITION_ADDRESSES = (21, 22, 23, 24, 25, 26, 27, 30, 31)


def _now():
    return datetime.now(timezone.utc).isoformat()


def _describe(error):
    return f"{type(error).__name__}: {error}" if error is not None else None


@dataclass(frozen=True)
class AcquisitionJobConfig:
    acquisition: AcquisitionConfig
    config_path: Path | None = None
    initialize_fpga: bool = False
    apply_defaults: bool = False

    def validate(self) -> None:
        self.acquisition.validate()
        for name in ("initialize_fpga", "apply_defaults"):
            if not isinstance(getattr(self, name), bool):
                raise ValueError(f"{name} must be boolean")

    def load_rows(self, existing=()) -> list[I2CRow]:
        self.validate()
        if self.config_path is None and existing:
            rows = deepcopy(list(existing))
        else:
            with Path(self.config_path or DEFAULT_CONFIG).open(newline="") as stream:
                rows = [I2CRow(int(r["add"]), int(r["subadd"]), r["data"].strip())
                        for r in csv.DictReader(stream)]
        keys = set()
        for row in rows:
            if not (0 <= row.add <= 255 and 0 <= row.subadd <= 255):
                raise ValueError("ASIC address/subaddress must be in range 0..255")
            if len(row.data) != 8 or set(row.data) - {"0", "1"}:
                raise ValueError(f"invalid ASIC data at {(row.add, row.subadd)}")
            key = (row.add, row.subadd)
            if key in keys:
                raise ValueError(f"duplicate ASIC row: {key}")
            keys.add(key)
        required = set(self.registers())
        # Discriminator-selection rows are generated by prepare_trigger_masks.
        required -= {(66, ch) for ch in range(N_CHANNELS)}
        missing = required - keys
        if missing:
            raise ValueError(f"configuration lacks acquisition registers: {sorted(missing)}")
        return rows

    def registers(self):
        acquisition = self.acquisition
        registers = [(66, ch) for ch in range(N_CHANNELS)]
        if acquisition.use_mask:
            registers += [(ch, 6) for ch in range(N_CHANNELS)]
        if acquisition.high_gain_code is not None or acquisition.low_gain_code is not None:
            registers += [(ch, ASIC_SHAPER_GAIN_SUBADDRESS) for ch in acquisition.channels]
        if acquisition.trigger_preamp_gain is not None:
            registers += [(ch, 1) for ch in acquisition.channels]
        if acquisition.threshold_dac is not None:
            registers += [(65, 2), (65, 1 if acquisition.t1 else 3)]
        registers.append((65, 12))
        return registers

    def as_dict(self):
        data = asdict(self)
        data["acquisition"]["out_dir"] = str(self.acquisition.out_dir)
        data["config_path"] = str(self.config_path) if self.config_path is not None else None
        return data


class AcquisitionJobError(RuntimeError):
    """Legacy API error carrying the complete partial result."""
    def __init__(self, result: AcquisitionResult):
        self.result = result
        super().__init__(_describe(result.error) or "; ".join(result.cleanup_errors + result.persistence_errors))


class AcquisitionJob:
    @staticmethod
    def preview(config: AcquisitionJobConfig) -> dict:
        config = deepcopy(config)
        config.load_rows()
        return {"execution_mode": "dry-run", "operation": config.as_dict(),
                "total_points": config.acquisition.batches,
                "temporary_asic_registers": len(config.registers()),
                "preparation_policy": "explicit initialization/defaults persist; temporary acquisition settings are restored"}

    def run(self, device: RadiorocDevice, config: AcquisitionJobConfig, *,
            metadata: RadiorocRunMetadata | None = None,
            cancellation: CancellationToken | None = None, on_event=None,
            verify_restoration: bool = False, append: bool = False) -> AcquisitionResult:
        """Return terminal status and partial paths, including on run failure.

        Invalid input, an occupied session or output collision raises before any
        hardware operation. Callbacks run on the caller's thread and must be quick;
        callback exceptions become warnings, never data loss or device failures.
        """
        config = deepcopy(config)
        if not isinstance(verify_restoration, bool):
            raise ValueError("verify_restoration must be boolean")
        if not isinstance(append, bool):
            raise ValueError("append must be boolean")
        rows = config.load_rows(device.i2c_rows)
        acquisition = config.acquisition
        total = acquisition.batches
        result = AcquisitionResult(csv_path=Path(acquisition.out_dir) / "events.csv",
                                   metadata=metadata, channels=list(acquisition.channels))
        result.status = "preparing"
        if device.dry_run:
            result.execution_mode = "dry-run"
            result.status = "completed"
            return result
        lock = session_lock(device.transport)
        if not lock.acquire(blocking=False):
            raise JobBusyError("another job is running on this transport session")
        try:
            return self._run_locked(device, config, rows, result, total,
                                    cancellation or CancellationToken(), on_event,
                                    verify_restoration, append)
        finally:
            lock.release()

    def _run_locked(self, device, config, rows, result, total, token, on_event,
                    verify_restoration, append):
        acquisition = config.acquisition
        mode = "simulation" if isinstance(device.transport, RadiorocMemoryTransport) else "hardware"
        result.execution_mode = mode
        source_files = sorted(Path(__file__).parents[1].rglob("*.py"))
        source_files.append(Path(__import__("radioroc_client").__file__))
        try:
            application_version = version("radioroc-tools")
        except PackageNotFoundError:
            application_version = "uninstalled-source"
        manifest = result.metadata.as_dict() if result.metadata else {}
        manifest.update({
            "schema_version": 1, "protocol_version": "legacy-framed-v1", "application_version": application_version,
            "source_fingerprint": sha256(b"".join(p.read_bytes() for p in source_files)).hexdigest(),
            "created_at": _now(), "status": "preparing", "execution_mode": mode,
            "operation": config.as_dict(), "units": {"ADC": "counts"},
            "board_identity": getattr(getattr(device.transport, "_lease", None), "identity", None),
            "effective_i2c_table": [asdict(row) for row in rows],
            "preparation": {"status": "not_started", "policy": "intentional changes persist"},
            "completed_points": 0, "total_points": total,
            "cleanup": {"status": "not_required", "errors": []},
            "device_state": "unobserved",
        })
        if mode == "simulation" and hasattr(device.transport, "simulation_metadata"):
            manifest["simulation"] = deepcopy(device.transport.simulation_metadata)
        writer = AcquisitionRunWriter(Path(acquisition.out_dir), manifest, append=append)
        result.metadata_path = writer.metadata_path
        fpga = {}
        asic = {}
        acquisition_started = False
        i2c_started = False
        preparation_failed = False
        snapshot = None
        previous_checkpoint = device._job_checkpoint
        device._job_checkpoint = token.checkpoint
        started_at = time.perf_counter()

        def emit(kind, *, batch=None, row=None, message=None):
            if on_event is not None:
                try:
                    on_event(JobEvent(kind, result.status, result.points, total, batch,
                                      tuple((row or {}).items()), message))
                except Exception as exc:
                    warning = f"progress callback failed: {_describe(exc)}"
                    if warning not in result.warnings:
                        result.warnings.append(warning)

        def persist():
            manifest.update(status=result.status, completed_points=result.points,
                            error=_describe(result.error),
                            error_notes=list(getattr(result.error, "__notes__", [])),
                            warnings=list(result.warnings), persistence_errors=list(result.persistence_errors))
            manifest["cleanup"] = {"status": result.cleanup_status, "errors": list(result.cleanup_errors)}
            writer.update(manifest)

        def cleanup_call(label, call):
            try:
                call()
            except BaseException as exc:
                result.cleanup_errors.append(f"{label}: {_describe(exc)}")

        try:
            emit("state")
            token.checkpoint()
            device.i2c_rows = rows
            firmware = device.read_word(100)
            manifest["firmware_status_word"] = firmware
            if result.metadata is not None:
                result.metadata.firmware_status_word = firmware
            manifest["preparation"]["status"] = "running"
            persist()
            preparation_failed = True
            if config.initialize_fpga:
                device.initialize_fpga()
            if config.apply_defaults:
                device.apply_default_config()
            preparation_failed = False
            manifest["preparation"]["status"] = "completed"
            # Capture control state before snapshot reads themselves use I2C.
            for address in _FPGA_ACQUISITION_ADDRESSES:
                fpga[address] = device.read_word(address)
            result.cleanup_status = "pending"
            manifest["device_state"] = "unknown_until_cleanup"
            persist()
            i2c_started = True
            keys = config.registers()
            values = device.read_fifo([I2CRow(a, s, "00000000") for a, s in keys])
            if len(values) != len(keys):
                raise TransportProtocolError(f"expected {len(keys)} snapshot bytes, received {len(values)}")
            asic = {key: bits(value) for key, value in zip(keys, values)}
            snapshot = {"fpga": dict(fpga), "asic": dict(asic)}
            manifest["snapshot"] = {"fpga": dict(fpga), "asic": [
                {"add": a, "subadd": s, "data": value} for (a, s), value in asic.items()]}
            persist()
            token.checkpoint()
            acquisition_started = True
            if acquisition.trigger_preamp_gain is not None:
                device.set_trigger_preamp_gain(acquisition.trigger_preamp_gain, channels=[acquisition.trigger_channel])
            device.set_energy_shaper_gain(channels=acquisition.channels, high_gain_code=acquisition.high_gain_code,
                                          low_gain_code=acquisition.low_gain_code)
            device.prepare_trigger_masks(t1=acquisition.t1, use_mask=acquisition.use_mask, use_ctest=False)
            if acquisition.use_mask:
                device.set_mask_for_channel(acquisition.trigger_channel, t1=acquisition.t1, enabled=True)
                # Genuine 2-distinct-channel coincidence (both coincidence-input
                # slots set to "Individual trigger"): unmask both named channels
                # at all three discriminator levels rather than guessing which
                # one "Individual trigger" taps -- see
                # RadiorocDevice.unmask_channel_for_individual_coincidence.
                if acquisition.trigger_type == 1 and acquisition.trigger_source == 3 \
                        and acquisition.trigger_source_2 == 3:
                    device.unmask_channel_for_individual_coincidence(acquisition.trigger_channel)
                    device.unmask_channel_for_individual_coincidence(acquisition.trigger_channel_2)
            if acquisition.threshold_dac is not None:
                device.set_threshold_dac(acquisition.threshold_dac, t1=acquisition.t1)
            result.status = "running"
            persist()
            emit("state")
            # The hold/timing operating point is fixed across all batches, so
            # it is applied once here rather than re-sent inside the loop;
            # acquire_adc_batch re-programs the nb_acq word itself every call.
            device.configure_adc_external_hold(
                trigger_channel=acquisition.trigger_channel, hold_delay_ns=acquisition.hold_delay_ns,
                conversion_delay_ns=acquisition.conversion_delay_ns, nb_acq=acquisition.acquisitions_per_batch,
                trigger_type=acquisition.trigger_type, trigger_source=acquisition.trigger_source,
                rstn_manual=acquisition.rstn_manual, ext_trig=False, peak_sensing=acquisition.peak_sensing,
                adc_window_ns=acquisition.adc_window_ns, adc_nb_trig=acquisition.adc_nb_trig,
                trigger_source_2=acquisition.trigger_source_2, trigger_channel_2=acquisition.trigger_channel_2)
            for batch_offset in range(acquisition.batches):
                token.checkpoint()
                batch = acquisition.start_batch + batch_offset
                high_gain, low_gain = device.acquire_adc_batch(
                    nb_acq=acquisition.acquisitions_per_batch, timeout_s=acquisition.timeout_s,
                    synchro_trigger=acquisition.synchro_trigger)
                token.checkpoint()
                event_rows = []
                for channel in acquisition.channels:
                    for event, (hg, lg) in enumerate(zip(high_gain[channel], low_gain[channel])):
                        event_rows.append({"batch": batch, "event": event, "channel": channel, "hg": hg, "lg": lg})
                writer.append_events(event_rows)
                result.points += 1
                persist()
                row = {f"ch{channel}_hg": list(high_gain[channel]) for channel in acquisition.channels}
                row.update({f"ch{channel}_lg": list(low_gain[channel]) for channel in acquisition.channels})
                emit("point", batch=batch, row=row)
            token.checkpoint()
            result.status = "completed"
        except (JobCancelled, KeyboardInterrupt) as exc:
            result.error = exc
            result.status = "cancelling"
            emit("state")
            result.status = "cancelled"
        except Exception as exc:
            result.error = exc
            result.status = "disconnected" if isinstance(exc, (TransportIOError, TransportClosedError)) else "failed"
        finally:
            device._job_checkpoint = None
            if preparation_failed:
                manifest["preparation"]["status"] = "failed_or_cancelled"
                result.cleanup_errors.append("preparation interrupted; intentional configuration may be partially applied")
            if acquisition_started:
                if acquisition.use_mask:
                    cleanup_call("prepare trigger masks",
                                 lambda: device.prepare_trigger_masks(t1=acquisition.t1, use_mask=True, use_ctest=False))
                for (add, subadd), value in asic.items():
                    cleanup_call(f"restore ASIC {add}/{subadd}",
                                 lambda a=add, s=subadd, v=value: device.write_register(a, s, v))
                for address, value in fpga.items():
                    cleanup_call(f"restore FPGA {address}",
                                 lambda a=address, v=value: device.write_word(a, v))
            if i2c_started:
                # Word 60 is a command strobe, not a restorable configuration.
                cleanup_call("idle I2C control", lambda: device.write_word(60, "00000000"))
            result.cleanup_status = "failed" if result.cleanup_errors else ("restored" if i2c_started else "not_required")
            if result.cleanup_errors and result.status == "completed":
                result.status = "failed"
            try:
                if verify_restoration:
                    result.verification = run_restoration_check(
                        device, snapshot, config.registers(), execution_mode=mode,
                        fpga_addresses=_FPGA_ACQUISITION_ADDRESSES)
                    manifest["verification"] = deepcopy(result.verification)
            except BaseException as exc:
                result.verification = {
                    "status": "failed", "execution_mode": mode,
                    "expected": {"fpga": [], "asic": []},
                    "observed": {"fpga_before_asic": [], "asic": [], "fpga_after_asic": []},
                    "mismatches": [], "missing": [],
                    "errors": [f"unexpected verifier failure: {_describe(exc)}"],
                    "cleanup": {"status": "failed", "word60_idle_attempted": False,
                                "word0_restore_attempted": False, "errors": []},
                }
                manifest["verification"] = deepcopy(result.verification)
            finally:
                device._job_checkpoint = previous_checkpoint
            manifest["finished_at"] = _now()
            manifest["elapsed_seconds"] = time.perf_counter() - started_at
            manifest["device_state"] = ("unknown" if result.cleanup_errors else
                                        ("restoration_commands_succeeded" if i2c_started else "unmodified_by_scan"))
            try:
                persist()
            except Exception as exc:
                result.persistence_errors.append(_describe(exc))
                if result.error is None:
                    result.error = exc
                if result.status == "completed":
                    result.status = "failed"
                try:
                    persist()
                except Exception as retry_error:
                    result.persistence_errors.append(_describe(retry_error))
            emit("state")
        return result
