"""One hold-scan workflow shared by the compatibility API, CLI and future UI.

The caller owns connection open/close. Preparation is intentional configuration;
scan settings are temporary and restored to the state after preparation.
"""

from copy import deepcopy
import csv
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from hashlib import sha256
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
import time

from radioroc_client import (
    ASIC_SHAPER_GAIN_SUBADDRESS, DEFAULT_CONFIG, HoldScanConfig, HoldScanResult, I2CRow,
    N_CHANNELS, RadiorocDevice, RadiorocMemoryTransport, RadiorocRunMetadata, bits, scan_values,
)
from radioroc.data.hold_scan import HoldRunWriter
from radioroc.transport.errors import TransportClosedError, TransportIOError, TransportProtocolError
from .jobs import CancellationToken, JobBusyError, JobCancelled, JobEvent, session_lock
from .verification import verify_restoration as run_restoration_check

# The job's own FPGA state footprint to snapshot/restore/verify: ADC hold/timing
# control words plus the IO mux words touched when sync_io_mux_index is set.
# Word 2 is excluded: acquire_adc_batch always leaves it exactly where it found it.
_FPGA_HOLD_ADDRESSES = (21, 22, 23, 24, 25, 26, 27, 30, 31, 77, 78)


def _now():
    return datetime.now(timezone.utc).isoformat()


def _describe(error):
    return f"{type(error).__name__}: {error}" if error is not None else None


@dataclass(frozen=True)
class HoldScanJobConfig:
    scan: HoldScanConfig
    config_path: Path | None = None
    initialize_fpga: bool = False
    apply_defaults: bool = False

    def validate(self) -> None:
        self.scan.validate()
        for name in ("initialize_fpga", "apply_defaults"):
            if not isinstance(getattr(self, name), bool):
                raise ValueError(f"{name} must be boolean")

    def load_rows(self, existing=()) -> list[I2CRow]:
        self.validate()
        if self.config_path is None and existing:
            rows = deepcopy(list(existing))
        else:
            with Path(self.config_path or DEFAULT_CONFIG).open(newline="") as stream:
                rows = [I2CRow(int(r["add"]), int(r["subadd"]), r["data"].strip())
                        for r in csv.DictReader(stream)]
        keys = set()
        for row in rows:
            if not (0 <= row.add <= 255 and 0 <= row.subadd <= 255):
                raise ValueError("ASIC address/subaddress must be in range 0..255")
            if len(row.data) != 8 or set(row.data) - {"0", "1"}:
                raise ValueError(f"invalid ASIC data at {(row.add, row.subadd)}")
            key = (row.add, row.subadd)
            if key in keys:
                raise ValueError(f"duplicate ASIC row: {key}")
            keys.add(key)
        required = set(self.registers())
        # Discriminator-selection rows are generated by prepare_trigger_masks.
        required -= {(66, ch) for ch in range(N_CHANNELS)}
        missing = required - keys
        if missing:
            raise ValueError(f"configuration lacks scan registers: {sorted(missing)}")
        return rows

    def registers(self):
        scan = self.scan
        registers = [(66, ch) for ch in range(N_CHANNELS)]
        if scan.use_mask:
            registers += [(ch, 6) for ch in range(N_CHANNELS)]
        if scan.use_ctest:
            registers += [(ch, 7) for ch in range(N_CHANNELS)]
        if scan.high_gain_code is not None or scan.low_gain_code is not None:
            registers += [(ch, ASIC_SHAPER_GAIN_SUBADDRESS) for ch in scan.channels]
        if scan.trigger_preamp_gain is not None:
            registers += [(ch, 1) for ch in scan.channels]
        if scan.threshold_dac is not None:
            registers += [(65, 2), (65, 1 if scan.t1 else 3)]
        registers.append((65, 12))
        if scan.mode == "internal":
            registers.append((65, 8))
        return registers

    def as_dict(self):
        data = asdict(self)
        data["scan"]["out_dir"] = str(self.scan.out_dir)
        data["config_path"] = str(self.config_path) if self.config_path is not None else None
        return data


class HoldScanJobError(RuntimeError):
    """Legacy API error carrying the complete partial result."""
    def __init__(self, result: HoldScanResult):
        self.result = result
        super().__init__(_describe(result.error) or "; ".join(result.cleanup_errors + result.persistence_errors))


class HoldScanJob:
    @staticmethod
    def preview(config: HoldScanJobConfig) -> dict:
        config = deepcopy(config)
        config.load_rows()
        count = len(scan_values(config.scan.hold_min, config.scan.hold_max, config.scan.hold_step, name="hold"))
        return {"execution_mode": "dry-run", "operation": config.as_dict(), "total_points": count,
                "temporary_asic_registers": len(config.registers()),
                "preparation_policy": "explicit initialization/defaults persist; temporary scan settings are restored"}

    def run(self, device: RadiorocDevice, config: HoldScanJobConfig, *,
            metadata: RadiorocRunMetadata | None = None,
            cancellation: CancellationToken | None = None, on_event=None,
            verify_restoration: bool = False) -> HoldScanResult:
        """Return terminal status and partial paths, including on run failure.

        Invalid input, an occupied session or output collision raises before any
        hardware operation. Callbacks run on the caller's thread and must be quick;
        callback exceptions become warnings, never data loss or device failures.
        """
        config = deepcopy(config)
        if not isinstance(verify_restoration, bool):
            raise ValueError("verify_restoration must be boolean")
        rows = config.load_rows(device.i2c_rows)
        scan = config.scan
        x_name = "hold_code" if scan.mode == "internal" else "hold_delay_ns"
        total = len(scan_values(scan.hold_min, scan.hold_max, scan.hold_step, name="hold"))
        result = HoldScanResult(csv_path=Path(scan.out_dir) / "holdscan.csv",
                                metadata=metadata, channels=list(scan.channels), mode=scan.mode)
        result.status = "preparing"
        if device.dry_run:
            result.execution_mode = "dry-run"
            result.status = "completed"
            return result
        lock = session_lock(device.transport)
        if not lock.acquire(blocking=False):
            raise JobBusyError("another job is running on this transport session")
        try:
            return self._run_locked(device, config, rows, result, total, x_name,
                                    cancellation or CancellationToken(), on_event,
                                    verify_restoration)
        finally:
            lock.release()

    def _run_locked(self, device, config, rows, result, total, x_name, token, on_event,
                    verify_restoration):
        scan = config.scan
        mode = "simulation" if isinstance(device.transport, RadiorocMemoryTransport) else "hardware"
        result.execution_mode = mode
        source_files = sorted(Path(__file__).parents[1].rglob("*.py"))
        source_files.append(Path(__import__("radioroc_client").__file__))
        try:
            application_version = version("radioroc-tools")
        except PackageNotFoundError:
            application_version = "uninstalled-source"
        manifest = result.metadata.as_dict() if result.metadata else {}
        manifest.update({
            "schema_version": 1, "protocol_version": "legacy-framed-v1", "application_version": application_version,
            "source_fingerprint": sha256(b"".join(p.read_bytes() for p in source_files)).hexdigest(),
            "created_at": _now(), "status": "preparing", "execution_mode": mode,
            "operation": config.as_dict(), "units": {"hold": "ns_or_code", "ADC": "counts"},
            "board_identity": getattr(getattr(device.transport, "_lease", None), "identity", None),
            "effective_i2c_table": [asdict(row) for row in rows],
            "preparation": {"status": "not_started", "policy": "intentional changes persist"},
            "completed_points": 0, "total_points": total,
            "cleanup": {"status": "not_required", "errors": []},
            "device_state": "unobserved",
        })
        if mode == "simulation" and hasattr(device.transport, "simulation_metadata"):
            manifest["simulation"] = deepcopy(device.transport.simulation_metadata)
        writer = HoldRunWriter(Path(scan.out_dir), scan.channels, manifest, x_name=x_name)
        result.metadata_path = writer.metadata_path
        fpga = {}
        asic = {}
        scan_started = False
        i2c_started = False
        preparation_failed = False
        snapshot = None
        previous_checkpoint = device._job_checkpoint
        device._job_checkpoint = token.checkpoint
        started_at = time.perf_counter()

        def emit(kind, *, hold_value=None, row=None, message=None):
            if on_event is not None:
                try:
                    on_event(JobEvent(kind, result.status, result.points, total, hold_value,
                                      tuple((row or {}).items()), message))
                except Exception as exc:
                    warning = f"progress callback failed: {_describe(exc)}"
                    if warning not in result.warnings:
                        result.warnings.append(warning)

        def persist():
            manifest.update(status=result.status, completed_points=result.points,
                            error=_describe(result.error),
                            error_notes=list(getattr(result.error, "__notes__", [])),
                            warnings=list(result.warnings), persistence_errors=list(result.persistence_errors))
            manifest["cleanup"] = {"status": result.cleanup_status, "errors": list(result.cleanup_errors)}
            writer.update(manifest)

        def cleanup_call(label, call):
            try:
                call()
            except BaseException as exc:
                result.cleanup_errors.append(f"{label}: {_describe(exc)}")

        try:
            emit("state")
            token.checkpoint()
            device.i2c_rows = rows
            firmware = device.read_word(100)
            manifest["firmware_status_word"] = firmware
            if result.metadata is not None:
                result.metadata.firmware_status_word = firmware
            manifest["preparation"]["status"] = "running"
            persist()
            preparation_failed = True
            if config.initialize_fpga:
                device.initialize_fpga()
            if config.apply_defaults:
                device.apply_default_config()
            preparation_failed = False
            manifest["preparation"]["status"] = "completed"
            # Capture control state before snapshot reads themselves use I2C.
            for address in _FPGA_HOLD_ADDRESSES:
                fpga[address] = device.read_word(address)
            result.cleanup_status = "pending"
            manifest["device_state"] = "unknown_until_cleanup"
            persist()
            i2c_started = True
            keys = config.registers()
            values = device.read_fifo([I2CRow(a, s, "00000000") for a, s in keys])
            if len(values) != len(keys):
                raise TransportProtocolError(f"expected {len(keys)} snapshot bytes, received {len(values)}")
            asic = {key: bits(value) for key, value in zip(keys, values)}
            snapshot = {"fpga": dict(fpga), "asic": dict(asic)}
            manifest["snapshot"] = {"fpga": dict(fpga), "asic": [
                {"add": a, "subadd": s, "data": value} for (a, s), value in asic.items()]}
            persist()
            token.checkpoint()
            scan_started = True
            if scan.trigger_preamp_gain is not None:
                device.set_trigger_preamp_gain(scan.trigger_preamp_gain, channels=scan.channels)
            device.set_energy_shaper_gain(channels=scan.channels, high_gain_code=scan.high_gain_code,
                                          low_gain_code=scan.low_gain_code)
            device.prepare_trigger_masks(t1=scan.t1, use_mask=scan.use_mask, use_ctest=scan.use_ctest)
            if scan.use_mask:
                device.set_mask_for_channel(scan.trigger_channel, t1=scan.t1, enabled=True)
            if scan.use_ctest:
                device.set_ctest_for_channel(scan.trigger_channel, enabled=True)
            if scan.threshold_dac is not None:
                device.set_threshold_dac(scan.threshold_dac, t1=scan.t1)
            if scan.sync_io_mux_index is not None:
                device.write_fpga_io_mux(**{scan.sync_io: scan.sync_io_mux_index})
            result.status = "running"
            persist()
            emit("state")
            for hold_value in scan_values(scan.hold_min, scan.hold_max, scan.hold_step, name="hold"):
                token.checkpoint()
                if scan.mode == "internal":
                    device.configure_adc_internal_hold(
                        trigger_channel=scan.trigger_channel, hold_code=hold_value, nb_acq=scan.acquisitions)
                else:
                    device.configure_adc_external_hold(
                        trigger_channel=scan.trigger_channel, hold_delay_ns=hold_value,
                        conversion_delay_ns=scan.conversion_delay_ns, nb_acq=scan.acquisitions,
                        trigger_type=scan.trigger_type, trigger_source=scan.trigger_source,
                        rstn_manual=scan.rstn_manual, ext_trig=scan.external_trigger,
                        peak_sensing=scan.peak_sensing, adc_window_ns=scan.adc_window_ns,
                        adc_nb_trig=scan.adc_nb_trig)
                high_gain, low_gain = device.acquire_adc_batch(
                    nb_acq=scan.acquisitions, timeout_s=scan.timeout_s, synchro_trigger=scan.synchro_trigger)
                token.checkpoint()
                row = {x_name: hold_value}
                for channel in scan.channels:
                    hg_mean, hg_stdev = device.mean_stdev(high_gain[channel])
                    lg_mean, lg_stdev = device.mean_stdev(low_gain[channel])
                    row[f"ch{channel}_hg_mean"] = hg_mean
                    row[f"ch{channel}_hg_stdev"] = hg_stdev
                    row[f"ch{channel}_lg_mean"] = lg_mean
                    row[f"ch{channel}_lg_stdev"] = lg_stdev
                    row[f"ch{channel}_count"] = len(high_gain[channel])
                writer.append_point(row)
                result.points += 1
                persist()
                emit("point", hold_value=hold_value, row=row)
            token.checkpoint()
            result.status = "completed"
        except (JobCancelled, KeyboardInterrupt) as exc:
            result.error = exc
            result.status = "cancelling"
            emit("state")
            result.status = "cancelled"
        except Exception as exc:
            result.error = exc
            result.status = "disconnected" if isinstance(exc, (TransportIOError, TransportClosedError)) else "failed"
        finally:
            device._job_checkpoint = None
            if preparation_failed:
                manifest["preparation"]["status"] = "failed_or_cancelled"
                result.cleanup_errors.append("preparation interrupted; intentional configuration may be partially applied")
            if scan_started:
                for (add, subadd), value in asic.items():
                    cleanup_call(f"restore ASIC {add}/{subadd}",
                                 lambda a=add, s=subadd, v=value: device.write_register(a, s, v))
                for address, value in fpga.items():
                    cleanup_call(f"restore FPGA {address}",
                                 lambda a=address, v=value: device.write_word(a, v))
            if i2c_started:
                # Word 60 is a command strobe, not a restorable configuration.
                cleanup_call("idle I2C control", lambda: device.write_word(60, "00000000"))
            result.cleanup_status = "failed" if result.cleanup_errors else ("restored" if i2c_started else "not_required")
            if result.cleanup_errors and result.status == "completed":
                result.status = "failed"
            try:
                if verify_restoration:
                    result.verification = run_restoration_check(
                        device, snapshot, config.registers(), execution_mode=mode,
                        fpga_addresses=_FPGA_HOLD_ADDRESSES)
                    manifest["verification"] = deepcopy(result.verification)
            except BaseException as exc:
                result.verification = {
                    "status": "failed", "execution_mode": mode,
                    "expected": {"fpga": [], "asic": []},
                    "observed": {"fpga_before_asic": [], "asic": [], "fpga_after_asic": []},
                    "mismatches": [], "missing": [],
                    "errors": [f"unexpected verifier failure: {_describe(exc)}"],
                    "cleanup": {"status": "failed", "word60_idle_attempted": False,
                                "word0_restore_attempted": False, "errors": []},
                }
                manifest["verification"] = deepcopy(result.verification)
            finally:
                device._job_checkpoint = previous_checkpoint
            manifest["finished_at"] = _now()
            manifest["elapsed_seconds"] = time.perf_counter() - started_at
            manifest["device_state"] = ("unknown" if result.cleanup_errors else
                                        ("restoration_commands_succeeded" if i2c_started else "unmodified_by_scan"))
            try:
                persist()
            except Exception as exc:
                result.persistence_errors.append(_describe(exc))
                if result.error is None:
                    result.error = exc
                if result.status == "completed":
                    result.status = "failed"
                try:
                    persist()
                except Exception as retry_error:
                    result.persistence_errors.append(_describe(retry_error))
            emit("state")
        return result
