"""One threshold workflow shared by the compatibility API, CLI and future UI.

The caller owns connection open/close. Preparation is intentional configuration;
scan settings are temporary and restored to the state after preparation.
"""

from copy import deepcopy
import csv
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from hashlib import sha256
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
import statistics
import time

from radioroc_client import (
    DEFAULT_CONFIG, I2CRow, RadiorocDevice, RadiorocMemoryTransport, RadiorocRunMetadata,
    ThresholdScanConfig, ThresholdScanResult, bits, scan_values,
)
from radioroc.data.threshold import ThresholdRunWriter
from radioroc.transport.errors import TransportClosedError, TransportIOError, TransportProtocolError
from .jobs import CancellationToken, JobBusyError, JobCancelled, JobEvent, session_lock


def _now():
    return datetime.now(timezone.utc).isoformat()


def _describe(error):
    return f"{type(error).__name__}: {error}" if error is not None else None


@dataclass(frozen=True)
class ThresholdJobConfig:
    scan: ThresholdScanConfig
    config_path: Path | None = None
    initialize_fpga: bool = False
    apply_defaults: bool = False

    def validate(self) -> None:
        self.scan.validate()
        for name in ("initialize_fpga", "apply_defaults"):
            if not isinstance(getattr(self, name), bool):
                raise ValueError(f"{name} must be boolean")

    def load_rows(self, existing=()) -> list[I2CRow]:
        self.validate()
        if self.config_path is None and existing:
            rows = deepcopy(list(existing))
        else:
            with Path(self.config_path or DEFAULT_CONFIG).open(newline="") as stream:
                rows = [I2CRow(int(r["add"]), int(r["subadd"]), r["data"].strip())
                        for r in csv.DictReader(stream)]
        keys = set()
        for row in rows:
            if not (0 <= row.add <= 255 and 0 <= row.subadd <= 255):
                raise ValueError("ASIC address/subaddress must be in range 0..255")
            if len(row.data) != 8 or set(row.data) - {"0", "1"}:
                raise ValueError(f"invalid ASIC data at {(row.add, row.subadd)}")
            key = (row.add, row.subadd)
            if key in keys:
                raise ValueError(f"duplicate ASIC row: {key}")
            keys.add(key)
        required = set(self.registers())
        # Discriminator-selection rows are generated by prepare_trigger_masks.
        required -= {(66, ch) for ch in range(64)}
        missing = required - keys
        if missing:
            raise ValueError(f"configuration lacks scan registers: {sorted(missing)}")
        return rows

    def registers(self):
        scan = self.scan
        registers = [(65, 2), (65, 1 if scan.t1 else 3)]
        registers += [(66, ch) for ch in range(64)]
        if scan.use_mask:
            registers += [(ch, 6) for ch in range(64)]
        if scan.use_ctest:
            registers += [(ch, 7) for ch in range(64)]
        if scan.trigger_preamp_gain is not None:
            registers += [(ch, 1) for ch in scan.channels]
        return registers

    def as_dict(self):
        data = asdict(self)
        data["scan"]["out_dir"] = str(self.scan.out_dir)
        data["config_path"] = str(self.config_path) if self.config_path is not None else None
        return data


class ThresholdJobError(RuntimeError):
    """Legacy API error carrying the complete partial result."""
    def __init__(self, result: ThresholdScanResult):
        self.result = result
        super().__init__(_describe(result.error) or "; ".join(result.cleanup_errors + result.persistence_errors))


class ThresholdJob:
    @staticmethod
    def preview(config: ThresholdJobConfig) -> dict:
        config = deepcopy(config)
        config.load_rows()
        count = len(scan_values(config.scan.dac_min, config.scan.dac_max, config.scan.dac_step))
        return {"execution_mode": "dry-run", "operation": config.as_dict(), "total_points": count,
                "counter_windows": count * len(config.scan.channels) * config.scan.averages,
                "temporary_asic_registers": len(config.registers()),
                "preparation_policy": "explicit initialization/defaults persist; temporary scan settings are restored"}

    def run(self, device: RadiorocDevice, config: ThresholdJobConfig, *,
            metadata: RadiorocRunMetadata | None = None,
            cancellation: CancellationToken | None = None, on_event=None) -> ThresholdScanResult:
        """Return terminal status and partial paths, including on run failure.

        Invalid input, an occupied session or output collision raises before any
        hardware operation. Callbacks run on the caller's thread and must be quick;
        callback exceptions become warnings, never data loss or device failures.
        """
        config = deepcopy(config)
        rows = config.load_rows(device.i2c_rows)
        scan = config.scan
        total = len(scan_values(scan.dac_min, scan.dac_max, scan.dac_step))
        result = ThresholdScanResult(csv_path=Path(scan.out_dir) / "thresholdscan.csv",
                                     metadata=metadata, channels=list(scan.channels), status="preparing")
        if device.dry_run:
            result.execution_mode = "dry-run"
            result.status = "completed"
            return result
        lock = session_lock(device.transport)
        if not lock.acquire(blocking=False):
            raise JobBusyError("another job is running on this transport session")
        try:
            return self._run_locked(device, config, rows, result, total,
                                    cancellation or CancellationToken(), on_event)
        finally:
            lock.release()

    def _run_locked(self, device, config, rows, result, total, token, on_event):
        scan = config.scan
        mode = "simulation" if isinstance(device.transport, RadiorocMemoryTransport) else "hardware"
        result.execution_mode = mode
        source_files = sorted(Path(__file__).parents[1].rglob("*.py"))
        source_files.append(Path(__import__("radioroc_client").__file__))
        try:
            application_version = version("radioroc-tools")
        except PackageNotFoundError:
            # Legacy scripts also run with dependencies alone, without installing
            # the project. The fingerprint still identifies the executed source.
            application_version = "uninstalled-source"
        manifest = result.metadata.as_dict() if result.metadata else {}
        manifest.update({
            "schema_version": 1, "protocol_version": "legacy-framed-v1", "application_version": application_version,
            "source_fingerprint": sha256(b"".join(p.read_bytes() for p in source_files)).hexdigest(),
            "created_at": _now(), "status": "preparing", "execution_mode": mode,
            "operation": config.as_dict(), "units": {"rate": "Hz", "window": "ms", "DAC": "code"},
            "board_identity": getattr(getattr(device.transport, "_lease", None), "identity", None),
            "effective_i2c_table": [asdict(row) for row in rows],
            "preparation": {"status": "not_started", "policy": "intentional changes persist"},
            "completed_points": 0, "completed_attempts": 0, "total_points": total,
            "cleanup": {"status": "not_required", "errors": []},
            "device_state": "unobserved",
        })
        writer = ThresholdRunWriter(Path(scan.out_dir), scan.channels, manifest)
        result.metadata_path = writer.metadata_path
        result.attempts_csv_path = writer.attempts_path
        fpga = {}
        asic = {}
        scan_started = False
        i2c_started = False
        preparation_failed = False
        previous_checkpoint = device._job_checkpoint
        device._job_checkpoint = token.checkpoint
        started_at = time.perf_counter()

        def emit(kind, *, dac=None, row=None, message=None):
            if on_event is not None:
                try:
                    on_event(JobEvent(kind, result.status, result.points, total, dac,
                                      tuple((row or {}).items()), message))
                except Exception as exc:
                    warning = f"progress callback failed: {_describe(exc)}"
                    if warning not in result.warnings:
                        result.warnings.append(warning)

        def persist():
            manifest.update(status=result.status, completed_points=result.points,
                            completed_attempts=result.attempts, error=_describe(result.error),
                            error_notes=list(getattr(result.error, "__notes__", [])),
                            warnings=list(result.warnings), persistence_errors=list(result.persistence_errors))
            manifest["cleanup"] = {"status": result.cleanup_status, "errors": list(result.cleanup_errors)}
            writer.update(manifest)

        def cleanup_call(label, call):
            try:
                call()
            except BaseException as exc:
                result.cleanup_errors.append(f"{label}: {_describe(exc)}")

        try:
            emit("state")
            token.checkpoint()
            device.i2c_rows = rows
            firmware = device.read_word(100)
            manifest["firmware_status_word"] = firmware
            if result.metadata is not None:
                result.metadata.firmware_status_word = firmware
            manifest["preparation"]["status"] = "running"
            persist()
            preparation_failed = True
            if config.initialize_fpga:
                device.initialize_fpga()
            if config.apply_defaults:
                device.apply_default_config()
            preparation_failed = False
            manifest["preparation"]["status"] = "completed"
            # Capture control state before snapshot reads themselves use I2C.
            for address in (0, 1, 6):
                fpga[address] = device.read_word(address)
            result.cleanup_status = "pending"
            manifest["device_state"] = "unknown_until_cleanup"
            persist()
            i2c_started = True
            keys = config.registers()
            values = device.read_fifo([I2CRow(a, s, "00000000") for a, s in keys])
            if len(values) != len(keys):
                raise TransportProtocolError(f"expected {len(keys)} snapshot bytes, received {len(values)}")
            asic = {key: bits(value) for key, value in zip(keys, values)}
            manifest["snapshot"] = {"fpga": dict(fpga), "asic": [
                {"add": a, "subadd": s, "data": value} for (a, s), value in asic.items()]}
            persist()
            token.checkpoint()
            scan_started = True
            if scan.trigger_preamp_gain is not None:
                device.set_trigger_preamp_gain(scan.trigger_preamp_gain, channels=scan.channels)
            device.prepare_trigger_masks(t1=scan.t1, use_mask=scan.use_mask, use_ctest=scan.use_ctest)
            saved_w1 = fpga[1]
            result.status = "running"
            persist()
            emit("state")
            for dac in scan_values(scan.dac_min, scan.dac_max, scan.dac_step):
                token.checkpoint()
                device.set_threshold_dac(dac, t1=scan.t1)
                row = {"DAC": dac}
                for channel in scan.channels:
                    device.write_word(6, bits(channel))
                    if scan.use_mask:
                        device.set_mask_for_channel(channel, t1=scan.t1, enabled=True)
                    if scan.use_ctest:
                        device.set_ctest_for_channel(channel, enabled=True)
                    rates = []
                    for attempt in range(1, scan.averages + 1):
                        for prefix in ("01", "00", "10"):
                            device.write_word(1, prefix + saved_w1[2:])
                        # Keep the existing high-resolution delay while checking
                        # cancellation at least every 10 ms during long windows.
                        deadline = time.perf_counter() + scan.trigger_window_ms / 1000.0
                        while True:
                            token.checkpoint()
                            remaining = (deadline - time.perf_counter()) * 1000.0
                            if remaining <= 0:
                                break
                            device.accurate_delay_ms(min(10.0, remaining))
                        device.write_word(1, "00" + saved_w1[2:])
                        token.checkpoint()
                        payload = device.transport.read_words(96, 4)
                        if len(payload) != 4:
                            raise TransportProtocolError("threshold counter requires four bytes")
                        count = int.from_bytes(payload, "little")
                        rate = count / (scan.trigger_window_ms / 1000.0)
                        writer.append_attempt({"DAC": dac, "channel": channel, "attempt": attempt,
                                               "rate_hz": round(rate, 6), "trigger_count": count})
                        result.attempts += 1
                        rates.append(rate)
                    row[f"ch{channel}"] = round(statistics.mean(rates), 6)
                    if scan.use_mask:
                        device.set_mask_for_channel(channel, t1=scan.t1, enabled=False)
                    if scan.use_ctest:
                        device.set_ctest_for_channel(channel, enabled=False)
                writer.append_point(row)
                result.points += 1
                persist()
                emit("point", dac=dac, row=row)
            token.checkpoint()
            result.status = "completed"
        except (JobCancelled, KeyboardInterrupt) as exc:
            result.error = exc
            result.status = "cancelling"
            emit("state")
            result.status = "cancelled"
        except Exception as exc:
            result.error = exc
            result.status = "disconnected" if isinstance(exc, (TransportIOError, TransportClosedError)) else "failed"
        finally:
            # Cancellation must not suppress cleanup, including repeated Ctrl-C.
            device._job_checkpoint = None
            if preparation_failed:
                manifest["preparation"]["status"] = "failed_or_cancelled"
                result.cleanup_errors.append("preparation interrupted; intentional configuration may be partially applied")
            if scan_started:
                cleanup_call("stop counter", lambda: device.write_word(1, "00" + fpga[1][2:]))
                for (add, subadd), value in asic.items():
                    cleanup_call(f"restore ASIC {add}/{subadd}",
                                 lambda a=add, s=subadd, v=value: device.write_register(a, s, v))
                cleanup_call("restore FPGA 6", lambda: device.write_word(6, fpga[6]))
            if i2c_started:
                # Word 60 is a command strobe, not a restorable configuration.
                cleanup_call("idle I2C control", lambda: device.write_word(60, "00000000"))
                cleanup_call("restore FPGA 0", lambda: device.write_word(0, fpga[0]))
            if scan_started:
                cleanup_call("restore FPGA 1", lambda: device.write_word(1, fpga[1]))
            device._job_checkpoint = previous_checkpoint
            result.cleanup_status = "failed" if result.cleanup_errors else ("restored" if i2c_started else "not_required")
            if result.cleanup_errors and result.status == "completed":
                result.status = "failed"
            manifest["finished_at"] = _now()
            manifest["elapsed_seconds"] = time.perf_counter() - started_at
            manifest["device_state"] = ("unknown" if result.cleanup_errors else
                                        ("restoration_commands_succeeded" if i2c_started else "unmodified_by_scan"))
            try:
                persist()
            except Exception as exc:
                result.persistence_errors.append(_describe(exc))
                if result.error is None:
                    result.error = exc
                if result.status == "completed":
                    result.status = "failed"
                # One attempt to record the storage failure itself. If storage
                # remains unavailable, the manifest may lag the returned result.
                try:
                    persist()
                except Exception as retry_error:
                    result.persistence_errors.append(_describe(retry_error))
            emit("state")
        return result
